[package]
name = "host"
version = "0.1.0"
authors = ["The Roc Contributors"]
license = "UPL-1.0"
edition = "2018"
#links = "app"

[lib]
name = "host"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "host"
path = "src/main.rs"

[dependencies]
roc_std = { path = "../../../roc_std" }
libc = "0.2"
wasm-bindgen = "0.2.80"
web-sys = { version = "0.3.57", features = [
    'Document',
    'Element',
    'HtmlElement',
    'Node',
    'Window',
]}

[workspace]
